name: Build and Run Tests
on: [pull_request]
jobs:
  build:
    name: Build and Run Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ["8", "11", "14"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Out Sources
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Confirm Java Version
        shell: bash
        run: javac -version

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test