name: Build and Run Tests
on:
  push:
    branches:
      - trunk
jobs:
  build:
    name: Build and Run Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ["8", "11", "14"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Out Sources
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Confirm Java Version
        shell: bash
        run: javac -version

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle

      - name: Docker Login
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u EventStore --password-stdin docker.pkg.github.com

      - name: Build and Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test

  publish:
    name: Publish Snapshot Packages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check Out Sources
        uses: actions/checkout@v1

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Confirm Java Version
        shell: bash
        run: javac -version

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ubuntu-latest-11-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ubuntu-latest-11-gradle

      - name: Publish GitHub Packages
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

